### ISSUE TITLE
Make sure tasks not available before open date

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-server#383]
During s014 demo, Phil was able to work a reading before it was open.  Make sure that 

1. We don't send tasks to the student via the API before the open date
2. We don't allow a student to work them before the open date.

/cc @philschatz

**Comment by Dantemss** [comment]
Done here: https://github.com/openstax/tutor-server/pull/397... at least (2)

**Comment by Dantemss** [comment]
As far as I understand, (1) is not what we want, since we want tasks that are "coming up"?

**Comment by philschatz** [comment]
I think I convinced @jason-holmes and @gregfitch that it's valuable to show the tasks in "Upcoming" but not make them clickable. Otherwise, the idea of a "Draft" is less useful.

**Comment by jpslav** [comment]
Yep and those should be showing up in the dashboard endpoint

**Comment by jason-holmes** [comment]
I just discussed this with Kathi…in the Coming Up area, she wants to only show Published items that are past the open date.

-------
Jason Holmes, Ph.D.
User Experience Manager
OpenStax | OpenStax.org
(713) 893-1326

**Comment by nathanstitt** [comment]
@jpslav Given the above, do we want the BE to no longer send the un-opened tasks, or should the FE just filter them out?

Filtering them out on FE is easy since I had that behavior implemented previously.  It would be just a matter of reversing the last few commits on PR #492 above.  The BE seems like it might be the proper place to do so though.

**Comment by Dantemss** [comment]
Going to ask during scrum.
