### ISSUE TITLE
Tutor should not display courses/error out for inactive students

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#638]

**Comment by jpslav** [comment]
Right now `/api/user/courses` returns courses that students have dropped (where the Student has a populated `inactive_at`).  This is causing issues because students are trying to access inactive courses from their dashboard, and since they have no active role they are getting errors.  While the long term solution might be to report all courses for a user and specify which are dropped/inactive, for right now let's just hide dropped courses for students.  

@Dantemss feel free to provide some guidance on where changes should happen.

**Comment by Dantemss** [comment]
I think the issue is mostly in `CollectCourseInfo`. An easy fix would be to just not return courses where the user has no roles.

Also for consistency, maybe `Role::GetUserRoles` shouldn't return inactive student roles (roles that have a `student` and the `student` object is inactive).
