### ISSUE TITLE
Moving student between periods needs to happen in a background job

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-server#717]
Mostly because we automatically assign all existing assignments in the new period to the student, which can take a long time (up to 2 minutes on QA).

(Right now teachers can DoS us by moving a lot of students back and forth, like Kajal just did to QA :) They are also pretty likely to do it because the moving student UI is kinda unresponsive)

**Comment by jpslav** [comment]
Actually can the moving of the student happen immediately, but the generation of assignments in a background job?  Seems like we want to move the student immediately so the UI can update right away --- I'm assuming the UI is unresponsive b/c the BE is slow, not because of a performance issue in the FE?

**Comment by Dantemss** [comment]
We could do it that way, yes.

**Comment by Dantemss** [comment]
UI is unresponsive because of BE.
